### PR TITLE
Adding unit test for folder rename - refs #26

### LINKED ISSUE #26: Undefinex index
After migrating from v7 to v8 I see plenty of those warnings. Here an example from the log:

``` json


{
  "reqId": "b18a58d2fcbc2576a17515262b1aa208",
  "remoteAddr": "58.28.152.233",
  "app": "PHP",
  "message": "Undefined index: \/var\/www\/owncloud\/data\/michael.heuberger\/files_encryption\/keys\/M1\/home\/michael-heuberger\/Music\/Blood Sugar Sex Magik at \/var\/www\/owncloud\/apps\/files_locking\/lib\/lockingwrapper.php#140",
  "level": 3,
  "time": "2015-05-06T04:08:40+00:00"
}

```

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@icewind1991 please review

@karlitschek fixes #26  and others

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Test first - this is the error as seen in #26 

```
There was 1 error:

1) OCA\Files_Locking\Tests\LockingWrapperTest::testRenameFolder

Undefined index: /tmp/oc_tmp_5LaVNR-folder/foo

/home/travis/build/owncloud/core/apps/files_locking/lib/lockingwrapper.php:140

/home/travis/build/owncloud/core/apps/files_locking/tests/LockingWrapperTest.php:100

```

**Comment by DeepDiver1975** [comment]
@jnfrmarks @SergioBertolinSG mind testing this one as well? THX

**Comment by DeepDiver1975** [comment]
fixes #8 @LukasReschke mind testing? THX

**Comment by LukasReschke** [comment]
Works :+1:

**Comment by DeepDiver1975** [comment]
THX @LukasReschke

**Comment by DeepDiver1975** [comment]
@karlitschek I'll prepare a PR for stable8 - people seem to have issue in 8.0.x as well

**Comment by karlitschek** [comment]
yes. backport is fine and important :+1:

**Pull request merged**
