### PR TITLE
Disable flock if transactional locking is enabled in core

### PR DESCRIPTION
**Pull request by PVince81**
@DeepDiver1975 @jnfrmarks @icewind1991 

It probably isn't useful to have both enabled at the same time.

### CODE REVIEW

**Comment by icewind1991** [comment]
Don't see a need for this, since the locking app needs to be enabled manually and they both work on a different level

**Comment by PVince81** [comment]
The files_locking is enabled by default I believe, at install time.

Let me change info.xml to disable it

**Comment by PVince81** [comment]
Hmmm, wait. People might still want to use it by default.

It's only when we make transactional locking the default that we can prevent this app from enabling itself.

**Comment by DeepDiver1975** [comment]
> It's only when we make transactional locking the default that we can prevent this app from enabling itself.

transactional locking is now enabled by default - I guess we can get rid of this app not - right?

@PVince81 @icewind1991 @schiesbn @karlitschek @cmonteroluque

**Comment by PVince81** [comment]
Yes. Note that this doesn't disable the app, just the functionality.

**Comment by DeepDiver1975** [comment]
> Yes. Note that this doesn't disable the app, just the functionality.

I'd go one step further and not longer ship the app with 8.2+

**Comment by MTRichards** [comment]
The only reason to keep it is that files locking leverages the OS level locking if it exists, and transaction locking does not. Is there ever a case where both would be useful to ensure corruption does not happen? Is flock faster? Is there something else?

**Comment by karlitschek** [comment]
Difficult to see the future is. ;-)  But I can't think of a usecase that is not covered with out transactional file locking. So I agree with Thomas that we should remove it.

**Comment by MTRichards** [comment]
images

**Comment by MTRichards** [comment]
I can't help feeling the dark side is at work here. BUT, I can't counter this because of a feeling, so OK! Remove for 9.0.

**Comment by LukasReschke** [comment]
Other approach at https://github.com/owncloud/files_locking/pull/46

**Comment by MorrisJobke** [comment]
> Other approach at #46

Was merged -> closing this one

**Pull request closed without merging**
